package input

type InputIDUser struct {
	ID int `uri:"id" binding:"required"`
}

type UserInput struct {
	Name           string `json:"name"`
	Email          string `json:"email"`
	PasswordHash   string `json:"password_hash"`
	AvatarFileName string `json:"avatar_file_name"`
	Role           string `json:"role"`
}

//Generated by Micagen at 15 November 2021
