package formatter

import "portfolio_api/entity"

type UserFormatter struct {
	ID             int    `json:"id"`
	Name           string `json:"name"`
	Email          string `json:"email"`
	PasswordHash   string `json:"password_hash"`
	AvatarFileName string `json:"avatar_file_name"`
	Role           string `json:"role"`
}

func FormatUser(user entity.User) UserFormatter {
	userFormatter := UserFormatter{}
	userFormatter.ID = user.ID
	userFormatter.Name = user.Name
	userFormatter.Email = user.Email
	userFormatter.PasswordHash = user.PasswordHash
	userFormatter.AvatarFileName = user.AvatarFileName
	userFormatter.Role = user.Role
	return userFormatter
}
func FormatUsers(users []entity.User) []UserFormatter {
	usersFormatter := []UserFormatter{}
	for _, user := range users {
		userFormatter := FormatUser(user)
		usersFormatter = append(usersFormatter, userFormatter)
	}
	return usersFormatter
}

//Generated by Micagen at 15 November 2021
